### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by joker5bb** [vanhoefm/modwifi-backports#1]
./gentree.py --clean --integrate --gitdebug /home/user/linux-next /home/user/Desktop
Copy original source files ...
Applying patches from patches to /home/user/Desktop/backports/ ...
Traceback (most recent call last):
  File "./gentree.py", line 1108, in <module>
    ret = _main()
  File "./gentree.py", line 724, in _main
    logwrite=logwrite)
  File "./gentree.py", line 915, in process
    kver = gen_version.kernelversion(bpid.project_dir)
  File "/home/user/modwifi-backports/lib/bpversion.py", line 40, in kernelversion
    _check(process)
  File "/home/user/modwifi-backports/lib/bpversion.py", line 11, in _check
    raise ExecutionError(process.returncode)
lib.bpversion.ExecutionError

**Comment by vanhoefm** [comment]
Using that command should not be needed when installing modwifi on a supported kernel. See the installation instructions at https://github.com/vanhoefm/modwifi

Getting it to work is tedious.. see the backports projects itself for advice on that.
